### ISSUE TITLE
Correção Iteração 0

### ISSUE THREAD

**Issue by ps1312** [chiuyong/iGuia#1]
## Preenchimento do GitHub:
* Nome do projeto -> ok
* Descrição do projeto -> ok
* Justificativa do projeto -> ok
* Especificação do papel dos membros -> ok
## Histórias de usuário:
* Formato -> ok
* História bem escrita -> ok
### nota final: 10
> Massa que vocês descreveram o máximo de hu's possíveis, mas não se limitem a isso. Se acharem que precisam de mais podem adicionar.

## Mockups e storyboards:
* Mockups -> ok
* Storyboard -> Não encontrei os storyboards de vocês, -5.
### nota final: 5
> Os mockups tão massa e bem desenhados porém vocês não colocaram nenhum storyboard mostrando o fluxo entre as páginas.

## Postmortem
* O que estava planejado -> ok
* O que foi feito -> ok
* O que não foi feito -> Não, coloquem pelo menos a seção com um "tudo foi realizado de acordo com o planejado", -1
* O que está planejado pra próxima iteração -> ok
* Lições aprendidas -> ok
* Formato Markdown -> ok
> Caras, vocês não denominaram responsáveis por nada, é essencial que vocês coloquem um nome a quem culpar no final das entregas para todas as seções do documento (quem era pra fazer cada coisa), -2 por isso.

**Comment by sotobr** [comment]
Alteração do postmortem da iteração 0 realizada
