### ISSUE TITLE
Feedback iteração 4 - Screencast

### ISSUE THREAD

**Issue by ps1312** [chiuyong/iGuia#27]
Pessoal, não encontrei o screencast de vcs..

**Comment by victorhcunha** [comment]
O nosso screencast está aqui:
https://drive.google.com/file/d/1R3Z6Vctgxuaz1WFxF4o09Z4gl71Bg56Z/view?usp=sharing

Em qual local do repositório ele deve ser colocado?

**Comment by ps1312** [comment]
Podem colocar dentro de alguma pasta de docs sem problema, mas vou ter que tirar 2 pontos pelo atraso na entrega..

**Comment by victorhcunha** [comment]
Os slides da última apresentação devem ser colocados no mesmo lugar?

**Comment by ps1312** [comment]
Sim, sem problemas
