### ISSUE TITLE
Feedback - Cadastrar histórias no gitHub 1IT

### ISSUE THREAD

**Issue by joismar** [chiuyong/iGuia#6]
Não há registro algum de historias de usuário nas issues, o é um dos principais critérios.
Nota: **2** (por terem uma boa cobertura de HUs já criada)

**Comment by chiuyong** [comment]
A gente já cadastrou todas as histórias na iteração 0

**Comment by joismar** [comment]
Por esse motivo dei nota 2 e não 0, pois este item verifica se as histórias foram corretamente a cadastradas como issues, não somente no documento de HUs, que foi corrigida na it0. 
Pode entrar em contato comigo lá no Telegram caso tenha alguma objeção.

**Comment by joismar** [comment]
Corrigido it1, não it2. Peço desculpas pelo erro na digitação.
